API rewritten to FastAPI
certtools/intelmq-api pull request #39
Opened 2022-12-22 10:19 UTC by kamil-certat

The FastAPI-based API is now an ASGI application, that isn't
natively supported by Apache. Instead, a recommended FastAPI
setup with web server Gunicorn is used. To keep backward compatibility,
Apache is still used as a Proxy. Apache and Gunicorn communicate
using unix socket.

The package installation creates intelmq-api service and socket
for systemd, and configure the Apache2 to communicate with them.
The INTELMQ_API_CONFIG env can now be set in the service unit file.

Provided configuration is an MVP and should be reviewed in the
production environement.

Depends on #38

2023-01-04 08:12 UTC, kamil-certat commented
The changes in compare to the #38 are visible here: https://github.com/kamil-certat/intelmq-api/pull/1

This PR is ready to review, but will be opened after merging the #38

2023-02-02 10:17 UTC, aaronkaplan commented
@kamil-certat I reviewed the PR. Could you please have a look at my comments, then I will be very happy to merge it in and test.
My main point - apart from the lots of little comments - is: did you test the old API vs. new API code?
Like are there any diffs when given the same input?

input -> old api -> output1
input -> new api -> output2

diff output1 output2 

?

2023-02-06 12:53 UTC, kamil-certat commented
@aaronkaplan I don't see any your comments, have you published them? The diff question answered in #38

2023-02-08 14:18 UTC, aaronkaplan commented
> @aaronkaplan I don't see any your comments, have you published them? The diff question answered in #38

Hm, yeah... you should see all my comments in the PR on github. Ping me in case you don't

2023-02-08 14:22 UTC, kamil-certat commented
I still don't see anything to address...

2023-02-08 14:35 UTC, aaronkaplan requested changes

2023-02-08 14:35 UTC, aaronkaplan commented on .github/workflows/code_style.yml
> +          python-version: 3.8
what about python 3.9, 3.10, 3.11?

2023-02-08 14:35 UTC, aaronkaplan commented on .github/workflows/mypy.yml
> +        python-version: [3.7, 3.8]
same... 3.9, 3.10, 3.11?

2023-02-08 14:35 UTC, aaronkaplan commented on .github/workflows/python-unittests.yml
> +        python-version: [3.7, 3.8]
same

2023-02-08 14:35 UTC, aaronkaplan commented on contrib/intelmq-api.service
> +WorkingDirectory=/usr/lib/python3/dist-packages/intelmq_api/
I might suggest to change the path  into a variable... why? different t linux distribs

2023-02-08 14:35 UTC, aaronkaplan commented on contrib/intelmq-api.socket
> +ListenStream=/usr/lib/python3/dist-packages/intelmq_api/intelmq_api.sock
Same here. the path might be distrib dependent. We also have Redhat users for example.

2023-02-08 14:35 UTC, aaronkaplan commented on debian/changelog
> +  * API rewritten to use the FastAPI framework
\o/

2023-02-08 14:35 UTC, aaronkaplan commented on intelmq_api/main.py
> +    intelmq_api.dependencies.startup(config)
just wondering why you use dependencies here... seems like extra complicated (-> KISS principle). Wouldn't it be enough to just call the loading of the config once here (I mean directly, without doing a dependency)?

2023-02-08 14:35 UTC, aaronkaplan commented on intelmq_api/main.py
> +app.include_router(api, prefix="/v1")
Are we compatible with the old API endpoint? I mean - should't we intentionally increase the API version number here?

2023-02-08 14:35 UTC, aaronkaplan commented on intelmq_api/intelmq-api.wsgi
> +
Is this file still needed? Or the TODO here?

2023-02-08 14:35 UTC, aaronkaplan commented on scripts/run_dev.sh
> +uvicorn intelmq_api.main:app --reload
--reload needed? I guess that depends on how we run it actually. In Docker, then yes probably...

2023-02-08 14:35 UTC, aaronkaplan commented on intelmq_api/version.py
> +__version_info__ = (3, 1, 0, 'rc2')
will need to be adapted for the final 3.1 rel. XXX TODO XXX

2023-02-08 14:35 UTC, aaronkaplan commented on intelmq_api/api.py
> +@api.get("/api/botnet", dependencies=[authorized])
isn't the new path /api/v1/... ?

2023-02-08 14:35 UTC, aaronkaplan commented on intelmq_api/dependencies.py
> +class OneTimeDependency(Generic[T]):
Do we need this type of dependency ? Or does it merely add lines of code.
KISS principle.

2023-02-08 14:35 UTC, aaronkaplan commented on intelmq_api/api.py
> +    if not set(id) < ID_CHARS:
elegant :)

2023-02-08 14:35 UTC, aaronkaplan commented on intelmq_api/api.py
> +class LoginForm(BaseModel):
(mior change request): I propose that we move all the fastAPI models to a separate python file.

2023-02-08 14:36 UTC, aaronkaplan commented
now?

2023-02-08 14:38 UTC, kamil-certat commented
Now I see, will answer shortly :)

2023-02-08 14:45 UTC, kamil-certat commented on .github/workflows/code_style.yml
> +          python-version: 3.8
We could do it, but please see this is just a style check, no unit tests run. I don't think it makes sense to run style check on every Python version. It may sometimes differ, but should not.

2023-02-08 14:47 UTC, kamil-certat commented on .github/workflows/mypy.yml
> +        python-version: [3.7, 3.8]
The same answer - I don't really think we need to run type check on every Python version. Let me know if you think it makes sense, then I'll do it.

2023-02-08 14:59 UTC, sebix commented
> @[aaronkaplan](https://github.com/aaronkaplan) aaronkaplan requested a review from [sebix](https://github.com/sebix)

Sorry, but I can't manage to review the API rewrite until Friday. That would include tests on various platforms, verifying documentation and examples and updating the package build instructions for multiple operating systems.

2023-02-08 15:10 UTC, kamil-certat commented on intelmq_api/api.py
> +class LoginForm(BaseModel):
Definitely good move!

2023-02-08 15:13 UTC, sebix commented on .github/workflows/code_style.yml
> +          python-version: 3.8
I agree with @kamil-certat

2023-02-08 15:14 UTC, kamil-certat commented
As I mentioned in some e-mail, there is trouble that for Debian < 11 packages for FastAPI don't exist. I think it would be a terrible exercise to prepare all of them in two days.

2023-02-08 15:14 UTC, sebix commented on .github/workflows/python-unittests.yml
> +        python-version: [3.7, 3.8]
Here I agree with @aaronkaplan to keep it in sync with the supported and tested platforms of intelmq (up to 3.11)

2023-02-08 15:23 UTC, kamil-certat commented on intelmq_api/dependencies.py
> +class OneTimeDependency(Generic[T]):
If we don't, then they will be loaded more than one time (on every request?). It could work, however I took a conservative approach to emulate how it was warking previously: this is exactly how we had it. There were no tests I can use to ensure that moving to typical dependencies doesn't break anything (like parallel access to sqllite etc.)

2023-02-08 15:24 UTC, kamil-certat commented on intelmq_api/main.py
> +app.include_router(api, prefix="/v1")
My idea and work was to be fully compatible

2023-02-08 15:24 UTC, kamil-certat commented on intelmq_api/api.py
> +@api.get("/api/botnet", dependencies=[authorized])
No, it's /v1/api/... - and the /v1/ is set in main.py

2023-02-08 15:24 UTC, kamil-certat commented on intelmq_api/api.py
> +    if not set(id) < ID_CHARS:
thanks :)

2023-02-08 15:25 UTC, kamil-certat commented on intelmq_api/intelmq-api.wsgi
> +
Ahh, leftover

2023-02-08 15:27 UTC, kamil-certat commented on scripts/run_dev.sh
> +uvicorn intelmq_api.main:app --reload
No, it's not nedded in Docker (why should be?), it's needed in development environement. The --reload keeps track on changed files and autmatically reload when something changed. It's just to help developers working on the API, and this script is just for developers.

2023-02-08 15:36 UTC, kamil-certat commented on intelmq_api/main.py
> +    intelmq_api.dependencies.startup(config)
I'm unsure if I understand you correctly.

This hook is calling a function from our module 'dependencies', that does exactly what you said - load config once, and save it in FastAPI-style dependencies. Then, FastAPI-dependencies are used to inject configuration or session store when processing requests. The one-time loading on startup is done to follow the previous solutions with globals, but in a clean way. Thanks to using dependencies, we can easily inject prepared configuration in tests.

2023-02-08 15:37 UTC, kamil-certat commented on .github/workflows/python-unittests.yml
> +        python-version: [3.7, 3.8]
Yeah, I've missed that place. Done.

2023-02-08 15:38 UTC, sebix requested changes
Did you verify that the packaging works on the supported plattforms?

2023-02-08 15:38 UTC, sebix commented on contrib/intelmq-api.socket
> +WantedBy=sockets.target
missing newline

2023-02-08 15:38 UTC, sebix commented on debian/install
> +contrib/intelmq-api.socket => /lib/systemd/system/intelmq-api.socket
missing newline

2023-02-08 15:38 UTC, sebix commented on debian/install
> +contrib/intelmq-api.service => /lib/systemd/system/intelmq-api.service
Are you sure that `/lib/systemd/` is the correct path?

2023-02-08 15:38 UTC, sebix commented on debian/postinst
> +		usermod -a -G intelmq www-data
strange indent

2023-02-08 15:38 UTC, sebix commented on contrib/api-apache.conf
> +<VirtualHost *:80>
This file is/was not a vhost definition, in other words, it's not placed in `/etc/apache2/sites-available/`, but in `/etc/apache2/conf-available/` (Debian-style paths), independent of the vhost definition and thus independent of any HTTPS vhost definition.

2023-02-08 15:38 UTC, sebix commented on contrib/intelmq-api.service
> +WantedBy=multi-user.target
missing newline

2023-02-08 15:38 UTC, sebix commented on contrib/intelmq-api.service
> +WorkingDirectory=/usr/lib/python3/dist-packages/intelmq_api/
The file is an example, and this path works on most distros. At least on all supported ones (Debian and Ubuntu, that is).

2023-02-08 15:42 UTC, kamil-certat commented on contrib/intelmq-api.service
> +WorkingDirectory=/usr/lib/python3/dist-packages/intelmq_api/
This is a good point, but I'm unsure how to solve it at the moment. The enviromental variable doesn't really makes sense - it should still need to be overriden by user, what is the same as override the WorkingDirectory directive... Do you have any ideas? Maybe the installation script should detect the platform?

2023-02-08 15:45 UTC, kamil-certat commented on contrib/api-apache.conf
> +      Require all granted
TODO: Ensure we still need it.

2023-02-08 15:45 UTC, kamil-certat commented on contrib/api-apache.conf
> +<VirtualHost *:80>
Fixed, thanks!

2023-02-08 15:49 UTC, kamil-certat commented on debian/install
> +contrib/intelmq-api.service => /lib/systemd/system/intelmq-api.service
For Debian, but not for RedHat... https://unix.stackexchange.com/a/458252

2023-02-08 15:50 UTC, kamil-certat commented on debian/postinst
> +		usermod -a -G intelmq www-data
No, let's open the file. It was strange previously ;)

2023-02-08 15:50 UTC, kamil-certat commented on intelmq_api/version.py
> +__version_info__ = (3, 1, 0, 'rc2')
Changed.

2023-02-08 15:55 UTC, kamil-certat commented
@sebix Unfortunately not, and this is why I wanted to separate rewrite and packaging at the beginning. It was, in fact, the first approach to package it.

It works on Debian 11, on the Debian 10 - as mentioned - we have lack of dependencies. RedHat's platform need to be tested.

2023-02-08 16:16 UTC, kamil-certat commented on contrib/api-apache.conf
> +      Require all granted
We don't.

2023-02-08 16:45 UTC, sebix commented on .gitignore
> +.vscode/
missing newline

2023-02-08 16:45 UTC, sebix commented on CHANGELOG.rst
> +- The packaging isn't yet prepared to work with FastAPI-based API.
Is this true? This PR changes a few files related to packaging

2023-02-09 09:15 UTC, aaronkaplan commented
> > @[aaronkaplan](https://github.com/aaronkaplan) aaronkaplan requested a review from [sebix](https://github.com/sebix)
> 
> Sorry, but I can't manage to review the API rewrite until Friday. That would include tests on various platforms, verifying documentation and examples and updating the package build instructions for multiple operating systems.

okay, got it. @kamil-certat would it be OK to put that into 3.2 then?

2023-02-13 08:43 UTC, kamil-certat commented on CHANGELOG.rst
> +- The packaging isn't yet prepared to work with FastAPI-based API.
Ugh, I missed this. I think my first idea was to separately handle API rewriting and packaging, bc I was expecting more troubles with packages than the API. This was written in the first PR.

2023-02-13 08:48 UTC, kamil-certat commented
I'm okay with this or just releasing API 3.1 a little later this week. Let me do additional tests and packaging fixes, hopefully today or tomorrow. If I fail with proper packaging until tomorrow, I may need help here if we want to finish this week.

And any additional testing is welcome :)

2023-02-13 08:54 UTC, kamil-certat commented
Anyway, I will not back-port dependencies for Debian 10 (or eventually CentOS, if needed) - will you eventually handle it during release packaging, @sebix?

2023-02-13 08:56 UTC, sebix commented
> Anyway, I will not back-port dependencies for Debian 10 (or eventually CentOS, if needed) - will you eventually handle it during release packaging, @sebix?

If there's no explicit contract or funding: No.

2023-02-13 09:26 UTC, kamil-certat commented
Sure, I understand it. Then we have a releasing issue because it works out-of-the-box for Debian 11, but will fail for the earlier.

@aaronkaplan: this is a question to you, how you think it's the best to handle it. I see the following options:
1) we can wait until someone find time to back-port dependencies (or maybe someone has already done it somewhere);
2) let's release API 3.1 with native packages for Debian 11, and leave systems without already built FastAPI on the PyPI packages as newest and 3.0.1 as native package (should work so far); change it once we find time to back-port dependencies. Already done native support doesn't look good: https://pkgs.org/search/?q=fastapi
3) abandon the FastAPI and look for a framework that is already widely supported; flask looks [promising](https://pkgs.org/search/?q=flask) and could be served as WSGI, so the same way as hug, by the Apache.

@sebix - is it possible to contribute to your building server?

2023-02-13 09:34 UTC, sebix commented
I don't think backporting fastapi. It has some dependencies which are not fulfilled in Debian 10, all of them need backports as well.

> @sebix - is it possible to contribute to your building server?

It's not _mine_, but a publicly usable instance. Contact me privately for the details (username etc.)

2023-02-13 09:49 UTC, kamil-certat commented
> I don't think backporting fastapi is useful. It has some dependencies which are not fulfilled in Debian 10, all of them need backports as well.

Yeah, it would need the full back-porting, the same way as we do with hug know. I'm also not a fan of maintaining all package dependencies on our own. So, what would you suggest? 

> t's not mine, but a publicly usable instance. Contact me privately for the details (username etc.)

I know, I called it yours because the repo is under your namespace (sebix/intelmq) ;) I'll contact you once I find it useful to change something :)

2023-02-15 12:48 UTC, kamil-certat commented
Okay, so after the mailing thread, my goals for packaging are:

1) native package for Debian 11 (all dependencies exists),
2) for other platforms, the pip package as recommended way.

To achieve 2) I'll update the documentation (PR https://github.com/certtools/intelmq/pull/2292) and try to prepare a script that should help with installing service units. In the future, it could be somehow integrated with `intelmqsetup` (but not at the moment, to not introduce additional complexity).

2023-02-15 12:54 UTC, aaronkaplan commented on intelmq_api/dependencies.py
> +class OneTimeDependency(Generic[T]):
I see, thanks for the explanations.

2023-02-15 12:56 UTC, aaronkaplan commented
> As I mentioned in some e-mail, there is trouble that for Debian < 11 packages for FastAPI don't exist. I think it would be a terrible exercise to prepare all of them in two days.

Yes, okay. Makes sense. So, what I propose is that we add a sentence to the documentation (if not already done) that only versions x,y,z are supported (Debian 11, Ubuntu  22, etc.) and what steps users of older OSes or other distros can do to get it running. OK?

2023-02-15 12:59 UTC, kamil-certat commented
Exactly

2023-02-15 15:57 UTC, kamil-certat commented
Please take a look now. I'll follow up tomorrow with final testing, today I didn't manage to finally test CentOS (some VirtualBox issues).

2023-03-24 11:39 UTC, sebix commented on contrib/api-apache.conf
> +# If you want to change default location, please allign the ROOT_PATH in the service configuration
typo "allign"

2023-05-17 16:45 UTC, aaronkaplan commented on .github/workflows/code_style.yml
> +          python-version: 3.8
then we leave it.

2023-05-17 16:45 UTC, aaronkaplan commented on .github/workflows/mypy.yml
> +        python-version: [3.7, 3.8]
convinced

2023-05-17 16:45 UTC, aaronkaplan commented on contrib/intelmq-api.service
> +WorkingDirectory=/usr/lib/python3/dist-packages/intelmq_api/
nope, then we leave it as is

2023-05-17 16:46 UTC, aaronkaplan commented on contrib/intelmq-api.socket
> +ListenStream=/usr/lib/python3/dist-packages/intelmq_api/intelmq_api.sock
leaving it since it's an example in contrib/

2023-05-17 16:46 UTC, aaronkaplan commented on intelmq_api/main.py
> +    intelmq_api.dependencies.startup(config)
its ok. I was just wondering.

2023-05-17 16:50 UTC, aaronkaplan commented on CHANGELOG.rst
> +- The packaging isn't yet prepared to work with FastAPI-based API.
so, is that fixed now or not?

2023-05-17 16:52 UTC, aaronkaplan approved these changes

2023-06-29 06:14 UTC, sebix requested changes
These packaged files are in the wrong location:
* `/etc/intelmq/intelmq-api.service`
* `/etc/intelmq/intelmq-api.socket`
* `/etc/intelmq/api-sudoers.conf`

The tests are not executed at build time:
```
[   56s]    dh_auto_test -O--buildsystem=pybuild
[   56s] I: pybuild base:232: cd /usr/src/packages/BUILD/.pybuild/cpython3_3.9/build; python3.9 -m unittest discover -v 
[   56s] 
[   56s] ----------------------------------------------------------------------
[   56s] Ran 0 tests in 0.000s
[   56s] 
[   56s] OK
```

2023-06-29 06:14 UTC, sebix commented on debian/control
>  Uploaders: Birger Schacht <schacht@cert.at>
this line needs a change too

2023-06-29 08:24 UTC, kamil-certat commented on debian/control
>  Uploaders: Birger Schacht <schacht@cert.at>
Good catch, but who should be there? I assume that you are the one, who looks the best as `Uploader`, aren't you?

2023-06-29 08:26 UTC, kamil-certat commented
Could you please elaborate, what do you mean by `wrong place`? Files you mentioned are in `/etc/intelmq` because of the `setup.py` configuration. The `/etc/intelmq/api-sudoers.conf` was always there. Do you mean, that we shouldn't include them in the python package, or in another dir? The Debian config placed them in the right dirs separately:

https://github.com/kamil-certat/intelmq-api/blob/727c3563cb79e72e770213ed739864e7ac683146/debian/install#L1-L5

2023-06-29 14:37 UTC, kamil-certat commented
re: tests. They were never running ;) https://build.opensuse.org/package/live_build_log/home:sebix:intelmq/intelmq-api/Debian_10/x86_64

We could make them working, but it would require downloading the IntelMQ package as Build-Depends in the build server. Do you know how to configure OBS to get package from another project?

2023-06-29 15:12 UTC, sebix commented
> Do you know how to configure OBS to get package from another project?

it will pick the intelmq package from the same repo (i.e. unstable). Why do you need another one? OBS uses the packages in the same project and then the repositories as defined per distributions (with preference on the local packages). I don't see a reason why you need to specify the project for your purpose.

> re: tests. They were never running ;) https://build.opensuse.org/package/live_build_log/home:sebix:intelmq/intelmq-api/Debian_10/x86_64

now we have better tests (previously only the session store was tested) and it makes more sense now

2023-06-29 15:12 UTC, sebix commented on debian/control
>  Uploaders: Birger Schacht <schacht@cert.at>
ack, makes sense

2023-06-30 09:15 UTC, sebix commented
> The `/etc/intelmq/api-sudoers.conf` was always there. Do you mean, that we shouldn't include them in the python package, or in another dir? The Debian config placed them in the right dirs separately:
> 
> https://github.com/kamil-certat/intelmq-api/blob/727c3563cb79e72e770213ed739864e7ac683146/debian/install#L1-L5

The Debian package does place them correctly but does not remove the files placed incorrectly by setuptools. To cut a long story short, I recommend (as the simplest and explicit solution) removing the wrongly placed files in the `debian/rules` file, section `override_dh_auto_install`:
```
rm debian/intelmq-api/etc/....
```

2023-07-03 07:46 UTC, kamil-certat commented
> it will pick the intelmq package from the same repo (i.e. unstable). Why do you need another one? OBS uses the packages in the same project and then the repositories as defined per distributions (with preference on the local packages). I don't see a reason why you need to specify the project for your purpose.

Okay, I'll try it :)

2023-07-11 14:55 UTC, kamil-certat commented
I fixed what you asked for @sebix 

However, building for Ubuntu 22.04 is broken due to the upstram bug: https://bugs.launchpad.net/ubuntu/+source/fastapi/+bug/1970557 Basically, the Ubuntu FastAPI and Starlette packages are out-of-sync in this version, and FastAPI is unable to work.

2023-07-17 07:13 UTC, sebix commented
> I fixed what you asked for @sebix

Thanks, let's merge then!

> However, building for Ubuntu 22.04 is broken due to the upstram bug: https://bugs.launchpad.net/ubuntu/+source/fastapi/+bug/1970557 Basically, the Ubuntu FastAPI and Starlette packages are out-of-sync in this version, and FastAPI is unable to work.

https://bugs.launchpad.net/ubuntu/+source/fastapi/+bug/1970557/comments/6 suggests that backporting 0.74.1-1 from Ubuntu 22.10 to Ubuntu 22.04 would work without requiring any updates of depending packages. Would this be a viable solution?

2023-07-17 07:15 UTC, sebix approved these changes

2023-07-17 07:15 UTC, merged